### PR TITLE
passwall: replace 'find' to 'type' for binary searching

### PR DESCRIPTION
**Pull request by peter-tank**
Signed-off-by: peter-tank <30540412+peter-tank@users.noreply.github.com>

### CODE REVIEW

**Comment by Lienol** [comment]
haproxy还是没运行，检测下

**Comment by handsomeji** [comment]
image
not run

**Comment by handsomeji** [comment]
@peter-tank 
I think sort_items has BUG.
When I use different load balancing port, can run.

**Comment by handsomeji** [comment]
image

**Comment by Lienol** [comment]
I also found this problem.

**Comment by peter-tank** [comment]
how about add an blank line to force end the listen section?
I checked the codes before changes, has a blank line there.
I tested on haproxy v1.5.18, no addtional blank line needed.
```
			cat <<-EOF >> "${haproxy_file}"

				listen $lport
```
```
	cat <<-EOF >> "${haproxy_file}"

		listen console
```

**Comment by Lienol** [comment]
No, It's actually return, it's not executed.
[ "${item}" != "hasvalid" ] && echolog "  - 没有发现任何有效节点信息..." && return 0

**Comment by peter-tank** [comment]
~~I noticed that you add `grep -v '^$'` to force remove the possible empty item, If `cut -s` realy fails on your side we should add it back.
Or maybe `sort_items="${sort_items:+${sort_items}${IFS}}${lport} ${item}"` for safe.~~ 

~~It's fine to just test `-n` for item, but should add `unset item` before the loop, or~~
should use another var name for any valid item checking.

**Pull request closed without merging**
