### PR TITLE
feat: hysteria2 support verify tls pinSHA256

### PR DESCRIPTION
**Pull request by Ariesly**
support using the pinSHA256 option to verify the server's certificate fingerprint.

### CODE REVIEW

**Comment by smallprogram** [comment]
Does it pass usability testing?

**Comment by Ariesly** [comment]
Not yet. pinSHA256 verification is not in effect.

I'm not sure if this is the right way to write it, so I'll try to adjust it later.         
```
pinSHA256 = (node.tls_pinSHA256) and node.tls_pinSHA256 or nil,
```

**Comment by Ariesly** [comment]
It should work this time

```tls_pinSHA256``` change to ```hysteria2_tls_pinSHA256```

```log
# when certificate fingerprint mismatch

failed to initialize client {"error": "connect error: CRYPTO_ERROR 0x12a (local): no certificate matches the pinned hash"}
```

**Comment by smallprogram** [comment]
> It should work this time
> 
> `tls_pinSHA256` change to `hysteria2_tls_pinSHA256`
> 
> ```
> # when certificate fingerprint mismatch
> 
> failed to initialize client {"error": "connect error: CRYPTO_ERROR 0x12a (local): no certificate matches the pinned hash"}
> ```

Good job~

**Pull request merged**
